// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dfwavqzaklquqzasevwm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRmd2F2cXpha2xxdXF6YXNldndtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ5NzA3MDYsImV4cCI6MjA2MDU0NjcwNn0.4lMFnNiqeY3aIFc4xhPR8vub_8E4QZGxQCE1QrZmnsI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);